config/routes.rb
Rails.application.routes.draw do
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'tech' => 'static_pages#tech'
  get 'exp' => 'static_pages#exp'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


 def hello
 	render text: "Welcome to Alex's Showcase Web Site"
 end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
  
  def tech
  end

  def exp
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title = '')
		base_title = "Alex Showcase"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Developed by Alex Lee
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "ALEX LEE", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About",   about_path %></li>

        
        <li><%= link_to "Experience",   exp_path %></li>
        <li><%= link_to "Contact",   contact_path %></li>

        
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>


    <h1>About</h1>
    <p>
		Alex is a web developer living and working in Seattle, USA. 

	He received his formal education in Civil and Environmental Engineering. After working in construction for several years, he decided to make a change, and has been developing since.

    </p>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Alex about a potential project at alex.lee.git at gmail.com
</p>

app/views/static_pages/exp.html.erb
<% provide(:title, 'Experience') %>
<h1>Experience</h1>
<p>
<body>

    <div id="page-wrap">
    	<%= link_to image_tag("AlexSmall.png", alt: "Profile Picture") %>
    
        <div id="contact-info" class="vcard">
        
            <!-- Microformats! -->
        
            <h1 class="fn">Alex Lee</h1>
        
            <p>
                Email: alex.lee.git at gmail.com
            </p>
        </div>
                
        <div id="objective">
            <p>

            </p>
        </div>
        
        <div class="clear"></div>
        
        <dl>
            <dd class="clear"></dd>
            
            <dt>Education</dt>
            <dd>
                <h2>University of Washington</h2>
                <p><strong>Major:</strong> Civil and Environmental Engineering<br />
                   
            </dd>
            
            <dd class="clear"></dd>
            
            <dt>Relevant Skills</dt>
            <dd>
                <h2>Information Technology</h2>
                <ul>
                	<li>Database Management, Development and Analytics skills, SQL</li>
	<li>Familiar with Microsoft stack, .net, C#, Matlab</li>
<li>Development: Ruby on Rails Framework, JavaScript, Version Control, Live Deployment</li>
<li>Proficient with HTML, CSS, Visio, Java, JavaScript, Python</li>
<li>Thorough knowledge and firsthand experience of Windows and UNIX systems, TCP/IP systems</li>
</ul>
                
                <h2>Engineering/Project Management</h2>
                <ul>
<li>Diverse Project Management and project pursuit experience across multiple disciplines</li>
	<li>Cost Management, CPM Scheduling,  and Business Intelligence skillset</li>
	<li>Strong CAD background</li>
<li>Frequent Client and Vendor interfacing; high levels of client satisfaction</li>
<li>Played key role for SAP and Sharepoint deployment and training</li>
<li>Field Operation, Spacial Planning  and Records Managements</li>
<li>Civil, Structural, and Geotechnical Engineering training</li>
                	</ul>
<h2>General</h2>

                <ul>
<li>Highly skilled with Microsoft Office Suite and Adobe inDesign, AutoCAD, Google Sketchup</li>
	<li>Extensive communication and interpersonal skills, including client relations</li>
	<li>Strong professional experience working with internal and external partners</li>
<li>Technical engineering background, analytical and problem solving skills; fast learner</li>
                	</ul>
            </dd>
            
            <dd class="clear"></dd>
            
            <dt>Experience</dt>
            <dd>
                <h2>Kiewit<span> Survey Project Engineer, SR 520 Floating Bridge Project, Bellevue, WA          12/2014 - 04/2015
</span></h2>
                <ul>
                    <li>Responsible for managing personnel and equipment for project survey department</li>
                    <li>Coordinated between multiple internal work groups, independent subcontractors and third party stakeholders to plan, schedule, and execute complex survey tasks</li>
                    <li>Developed alignments and models in AutoCad Civil 3D for geometric take-offs and construction data</li>
                    <li>Coordinated with project team to determine survey needs and controls on operational basis</li>

                </ul>
                
                <h2>Kiewit <span>Project Scheduler, SR 520 Floating Bridge Project, Bellevue, WA                       02/2014 - 11/2014</span></h2>
                <ul>
                    <li> Responsible for developing project progress documentation and communication to client, executing multi-million dollar pay applications. With the execution of a major delay based change order, I reestablished the baseline schedule through coordination with client personnel and internal partners. The client staff stated it was the most positive experience they’d had with a scheduler on a the project.</li>
                                        <li>Created Time Impact Analysis Schedules to analyze the effects of delays to the project</li>
                    <li>Further developed relationship skills through communication with client personnel</li>

                </ul> 
            </dd>
            
            <dd class="clear"></dd>
            
          
            <dt>References</dt>
            <dd>Available on request</dd>
            
            <dd class="clear"></dd>
        </dl>
        
        <div class="clear"></div>
    
    </div>

</body>

</html>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>


    <h1>Help</h1>
    <p>
		If you have any questions about the web site. or need some help, please feel free to contact me at alex.lee.git at gmail.com

    </p>

app/views/static_pages/home.html.erb
<div class="center jumbortron">
	<h1>Alex Lee, Developer</h1>

	<h2>This is the home page for a Web Site to highlight Alex Lee's talents and experience.</h2>

</div>

<%= link_to image_tag("AlexLeePhoto.jpg", alt: "Profile Picture"),
            'http://google.com/' %>

app/views/static_pages/tech.html.erb
tech.html.erb